import './adapter-cases/model-client-1.cases.js'
import './adapter-cases/model-client-2.cases.js'
import './adapter-cases/model-client-3.cases.js'
import './adapter-cases/model-client-4.cases.js'
import './adapter-cases/model-client-5.cases.js'
import './adapter-cases/model-client-6.cases.js'
